quarkus.log.console.format=%d{HH:mm:ss.SSS} %-5p [%t] %c - %s%e%n

quarkus.test.continuous-testing=disabled

#quarkus.vertx.max-event-loop-execute-time=10000
#quarkus.vertx.max-worker-execute-time=2m


#quarkus.vertx.event-loops-pool-size=200

# quarkus.vertx.worker-pool-size=20